### ISSUE TITLE
Feature request: limitation of download/upload speed

### ISSUE THREAD

**Issue by shoichikaji** [dagolden/HTTP-Tiny-UA#10]
I sometimes want to limit download/upload speed.

I tried to implement this feature in https://github.com/shoichikaji/HTTP-Tiny-Bandwidth

If HTTP::Tiny::UA would accept this feature, I'm happy to raise a pull request.
What do you think?
Thanks.

**Comment by xdg** [comment]
It's a very interesting idea.  Unfortunately, I think HTTP::Tiny::UA isn't the right place for it.  It would seem more interesting to find a way to make a generic "callback rate limiter" module for CPAN, perhaps.  (I.e. wrapping an arbitrary user function).  Then the HTTP::Tiny (and ::UA) docs could reference it as an option.
