### ISSUE TITLE
Drop superclass dep.

### ISSUE THREAD

**Issue by EvanCarroll** [dagolden/HTTP-Tiny-UA#18]
I know it may seem like a good idea, but `superclass` is adding another dep and bringing in `Module::Load` to do little more than what Perl currently handles with a Makefile. It would be my preference to `use parent`. If you want to version the modules, just eq against `$HTTP::Tiny::VERSION`.

I know you created it, cool idea, perhaps you could get it into core instead.

**Comment by xdg** [comment]
I understand your concern, but don't plan to change it.  You're welcome to fork if if you want a dependency-light version.
